name: eng_word_storage
description: A word storage application for language learning
version: 1.1.0+18

environment:
    sdk: '>=3.1.5 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    sqflite: ^2.3.0
    path: ^1.8.3
    shared_preferences: ^2.2.2
    flutter_slidable: ^3.0.1
    fluttertoast: ^8.2.4
    path_provider: ^2.1.2
    flutter_tts: ^3.8.5
    cupertino_icons: ^1.0.8
    intl: ^0.19.0
    file_picker: ^6.1.1
    share_plus: ^7.2.1
    permission_handler: ^11.1.0
    url_launcher: ^6.2.4
    package_info_plus: ^5.0.1
    font_awesome_flutter: ^10.6.0
    google_mobile_ads: ^5.0.0
    firebase_core: ^2.24.2
    firebase_analytics: ^10.7.4
    in_app_purchase: ^3.2.0
    firebase_remote_config: ^4.3.8
    easy_localization: ^3.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    flutter_launcher_icons: ^0.9.2

flutter_icons:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path: 'assets/images/dog_icon_min.png'
    adaptive_icon_background: '#253580'
    adaptive_icon_foreground: 'assets/images/for_android.png'

flutter:
    uses-material-design: true
    assets:
        - assets/images/dog.png
        - assets/translations/
